package edu.kit.quak.infrastructure.circuit.in.web.rest.mapper;

import edu.kit.quak.core.circuit.model.QuantumCircuit;
import edu.kit.quak.core.circuit.model.register.QuantumRegister;
import edu.kit.quak.infrastructure.circuit.in.web.rest.dto.CircuitResponse;
import edu.kit.quak.infrastructure.circuit.in.web.rest.dto.QubitResponse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;
import java.util.Objects;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING,
        uses = { QubitDtoMapper.class })
public abstract class CircuitDtoMapper {
    @Autowired //SonarQube suggests switching to constructor injection, but then the mapper would no longer work.
    protected QubitDtoMapper qubitDtoMapper;

    @Mapping(target = "qubits", source = "registers")
    public abstract CircuitResponse toResponse(QuantumCircuit circuit);

    // Note: This method is used in the impl class generated by MapStruct.
    protected List<QubitResponse> mapRegistersToQubits(List<QuantumRegister> registers) {
        if (registers == null) return List.of();

        return registers.stream()
                .filter(Objects::nonNull)
                .flatMap(reg -> reg.getQubits().stream()
                        .map(qubit -> qubitDtoMapper.toResponse(qubit, reg.getName())))
                .toList();
    }
}