package edu.kit.quak.infrastructure.circuit.in.web.rest.mapper;

import static org.junit.jupiter.api.Assertions.*;

import edu.kit.quak.core.circuit.model.layer.operation.ElementSelector;
import edu.kit.quak.core.circuit.model.layer.operation.ElementaryQuantumGate;
import edu.kit.quak.core.circuit.model.layer.operation.Measurement;
import edu.kit.quak.core.circuit.model.layer.operation.QuantumOperation;
import edu.kit.quak.core.circuit.model.layer.operation.library.QuantumOperationLibrary;
import edu.kit.quak.infrastructure.circuit.in.web.rest.dto.ElementSelectorDto;
import edu.kit.quak.infrastructure.circuit.in.web.rest.dto.ElementaryQuantumGateDto;
import edu.kit.quak.infrastructure.circuit.in.web.rest.dto.MeasurementDto;
import edu.kit.quak.infrastructure.circuit.in.web.rest.dto.QuantumOperationDto;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Spy;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class QuantumOperationDtoMapperTest {

    @Spy
    private ElementSelectorDtoMapperImpl qubitSelectorDtoMapper;

    @InjectMocks
    private QuantumOperationDtoMapperImpl mapper;

    @Test
    void toResponse() {
        // Arrange
        ElementSelector target = new ElementSelector("reg_id", 0);
        ElementSelector classicBit = new ElementSelector("reg_id", 1);

        ElementaryQuantumGate gate = new ElementaryQuantumGate(QuantumOperationLibrary.X, false, List.of(target), null, 0d);
        Measurement measurement = new Measurement(QuantumOperationLibrary.MEASURE, false, List.of(target), null, List.of(classicBit));

        // Act
        QuantumOperationDto gateResponse = mapper.toResponse(gate);
        QuantumOperationDto measurementResponse = mapper.toResponse(measurement);

        // Assert
        assertNotNull(gateResponse);
        assertEquals(gate.getId(), gateResponse.getId());
        assertEquals(QuantumOperationLibrary.X.name(), gateResponse.getIdentifier());

        assertNotNull(measurementResponse);
        assertEquals(measurement.getId(), measurementResponse.getId());
        assertEquals(QuantumOperationLibrary.MEASURE.name(), measurementResponse.getIdentifier());
    }

    @Test
    void toDomain() {
        // Arrange
        ElementSelectorDto target = new ElementSelectorDto("reg_id", 0);
        ElementSelectorDto classicBit = new ElementSelectorDto("reg_id", 1);

        ElementaryQuantumGateDto gateDto = new ElementaryQuantumGateDto(
            "id",
            QuantumOperationLibrary.X.name(),
            false,
            List.of(target),
            null,
            0d
        );
        MeasurementDto measurementDto = new MeasurementDto(
            "id",
            QuantumOperationLibrary.MEASURE.name(),
            false,
            List.of(target),
            null,
            List.of(classicBit)
        );

        // Act
        QuantumOperation gate = mapper.toDomain(gateDto);
        QuantumOperation measurement = mapper.toDomain(measurementDto);

        // Assert
        assertNotNull(gate);
        assertNotEquals(gateDto.getId(), gate.getId()); // ID should be generated by domain
        assertEquals(QuantumOperationLibrary.X, gate.getOperationDefinition());

        assertNotNull(measurement);
        assertNotEquals(measurementDto.getId(), measurement.getId()); // ID should be generated by domain
        assertEquals(QuantumOperationLibrary.MEASURE, measurement.getOperationDefinition());
    }
}
