package edu.kit.quak.application.filesystem.services;

import edu.kit.quak.application.filesystem.delegator.FileElementContainerRepositoryDelegator;
import edu.kit.quak.application.filesystem.exceptions.AccessDeniedException;
import edu.kit.quak.core.filesystem.model.FileElement;
import edu.kit.quak.core.filesystem.model.FileElementContainer;
import edu.kit.quak.core.user.model.User;
import java.util.UUID;
import java.util.function.Consumer;
import lombok.extern.slf4j.Slf4j;

/**
 * Abstract base class for file element services that provides common functionality for ownership
 * verification, parent retrieval, and element modification operations.
 *
 * <p>This class eliminates code duplication across DirectoryService and FileService by extracting
 * shared logic for:
 *
 * <ul>
 *   <li>Ownership verification using efficient recursive CTE queries
 *   <li>Parent container retrieval
 *   <li>Finding elements within parent containers
 *   <li>Modifying elements within their parent context
 * </ul>
 *
 * @param <T> the type of FileElement this service manages (File, Directory, etc.)
 * @author Generated by refactoring
 */
@Slf4j
public abstract class AbstractFileElementService<T extends FileElement<T>> {

    protected final FileElementContainerRepositoryDelegator delegator;

    protected AbstractFileElementService(FileElementContainerRepositoryDelegator delegator) {
        this.delegator = delegator;
    }

    /**
     * Verifies that the given user owns the project containing the file/directory. Uses a single
     * efficient database query with recursive CTE to find the root project's owner, avoiding N+1
     * queries when traversing deep hierarchies.
     *
     * @param parentId the ID of the parent container
     * @param user the user to verify ownership for
     * @throws AccessDeniedException if user doesn't own the project
     */
    protected void verifyOwnershipByParentId(String parentId, User user) {
        if (parentId == null) {
            throw new IllegalStateException("Cannot verify ownership: element has no parent");
        }

        // Use efficient single-query ownership lookup
        UUID projectOwnerId = delegator
            .findProjectOwnerIdByElementId(parentId)
            .orElseThrow(() -> new IllegalStateException("Could not find root project for element with" + " parent ID: " + parentId));

        if (!projectOwnerId.equals(user.getId())) {
            log.warn(
                "Access denied: User '{}' is not owner of project '{}' ({} parent: '{}')",
                user.getId(),
                projectOwnerId,
                getElementTypeName(),
                parentId
            );
            throw new AccessDeniedException(getElementTypeName(), parentId);
        }
    }

    /**
     * Retrieves the parent container by ID.
     *
     * @param parentId the ID of the parent container
     * @return the parent container
     * @throws IllegalStateException if parent is null or not found
     */
    protected FileElementContainer<?> getParentById(String parentId) {
        if (parentId == null) {
            throw new IllegalStateException(getElementTypeName() + " has no parent - corrupt state");
        }
        return delegator.findContainerById(parentId).orElseThrow(() -> new IllegalStateException("Parent not found with ID: " + parentId));
    }

    /**
     * Finds a specific element within its parent container.
     *
     * @param parent the parent container
     * @param elementId the ID of the element to find
     * @return the found element
     * @throws IllegalStateException if element is not found in parent
     */
    protected T findElementInParent(FileElementContainer<?> parent, String elementId) {
        return parent
            .getContents()
            .stream()
            .filter(c -> c.getId().equals(elementId))
            .filter(this::isCorrectType)
            .map(this::castToType)
            .findFirst()
            .orElseThrow(() -> new IllegalStateException(getElementTypeName() + " not found in parent container (ID: " + elementId + ")"));
    }

    /**
     * Modifies an element within its parent context and persists the changes.
     *
     * @param elementId the ID of the element to modify
     * @param modifier the modification function to apply
     * @return the modified element
     */
    protected T modifyElementInParent(String elementId, Consumer<T> modifier) {
        T tempElement = retrieveWithoutAuth(elementId);
        FileElementContainer<?> parent = getParentById(tempElement.getParentId());

        // Finding the "real" child in the context of the parent
        T childInParent = findElementInParent(parent, elementId);

        // Apply changes
        modifier.accept(childInParent);

        // Save changes through parent
        FileElementContainer<?> savedParent = delegator.save(parent);

        // Return updated child
        return findElementInParent(savedParent, elementId);
    }

    /**
     * Retrieves an element by ID without authentication check. Should only be used internally.
     *
     * @param id the ID of the element
     * @return the element
     */
    protected abstract T retrieveWithoutAuth(String id);

    /**
     * Returns the name of the element type for logging and error messages.
     *
     * @return the element type name (e.g., "file", "directory")
     */
    protected abstract String getElementTypeName();

    /**
     * Checks if a FileElement is of the correct type for this service.
     *
     * @param element the element to check
     * @return true if the element is of the correct type
     */
    protected abstract boolean isCorrectType(FileElement<?> element);

    /**
     * Casts a FileElement to the specific type managed by this service.
     *
     * @param element the element to cast
     * @return the casted element
     */
    protected abstract T castToType(FileElement<?> element);
}
