import { isCompositeGate, QuantumOperationDto } from '@/api/dto/circuit.ts';

/**
 * A copy of an operation under a fresh identity, nested bodies included.
 *
 * Operation ids are client-generated and stable across saves, so anything that *duplicates* an
 * operation — dropping a gate from the library, dissolving a box into its parts — has to mint new
 * ones rather than carry the source's along. The recursion matters for composites: a body's ids are
 * regenerated by the backend on every read and are not the ids of the rows it is stored in, so
 * reusing them would leave two operations in one circuit claiming the same identity.
 */
export const withFreshIds = (operation: QuantumOperationDto): QuantumOperationDto => {
    const copy = { ...operation, id: crypto.randomUUID() };
    return isCompositeGate(copy) ? { ...copy, body: (copy.body ?? []).map(withFreshIds) } : copy;
};
