[#-- Renders THIRD-PARTY-LICENSES.md from an ORT result. Used by .github/workflows/licenses.yml. --]
[#assign view = LicenseView.CONCLUDED_OR_DECLARED_AND_DETECTED]
[#assign shipped = packages?filter(p -> !p.excluded)]
[#assign ecosystems = [
    {"type": "Maven", "title": "Backend (Gradle)"},
    {"type": "NPM", "title": "Web app and VS Code extension (npm)"},
    {"type": "PyPI", "title": "Python language server (pip)"},
    {"type": "Go", "title": "OpenQASM language server (Go)"}
]]
[#assign licenseIds = []]
# Third-party licenses

QuaK is licensed under the [MIT License](LICENSE). It ships the third-party packages listed below.

This file is generated by the [OSS Review Toolkit](https://oss-review-toolkit.org/) in
`.github/workflows/licenses.yml`. Do not edit it by hand.
[#list ecosystems as ecosystem]
    [#assign group = shipped?filter(p -> p.id.type == ecosystem.type)]
    [#if !group?has_content][#continue][/#if]

## ${ecosystem.title}

| Package | Version | License |
|---|---|---|
    [#list group as package]
        [#assign license = package.license.effectiveLicense(view, package.licenseChoices)!]
        [#assign metadata = helper.getPackage(package.id)]
        [#assign name][#if package.id.namespace?has_content]${package.id.namespace}:[/#if]${package.id.name}[/#assign]
        [#assign url = metadata.homepageUrl?has_content?then(metadata.homepageUrl, metadata.vcsProcessed.url)]
| [#if url?has_content][${name}](${url})[#else]${name}[/#if] | ${package.id.version} | [#if license?has_content]${license}[#else]unknown[/#if] |
        [#if license?has_content]
            [#list license.decompose() as single]
                [#list [single.simpleLicense(), single.exception()!""] as id]
                    [#if id?has_content && !licenseIds?seq_contains(id)][#assign licenseIds = licenseIds + [id]][/#if]
                [/#list]
            [/#list]
        [/#if]
    [/#list]
[/#list]

## License texts
[#list licenseIds?sort as id]
    [#assign text = licenseFactProvider.getLicenseText(id)!]

### ${id}

    [#if text?has_content]
```text
${text?trim}
```
    [#else]
No license text is available for ${id}. See the package links above.
    [/#if]
[/#list]
